on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu la-test
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version : 12.x
      - run : npm i
      - run : npm run start:dev
