on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version : 12.x
      - run : npm i
      
      - name: Check Coverage TDD
        run : npm run test:cov
        
      - name: Upload
        uses: codecov/codecov-action@v1
        with:
          files: ./lib.c.gcov
    
