on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version : 12.x
      - run : npm i
      
      - name: Check Coverage TDD
        run : npm run test:cov
        
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: 54fbb25c-4811-4fa0-9ee8-5ed7c4879812
          flags: unittests



  deploy-dev:
    runs-on: ubuntu-latest
    environment: 
      name : dev
      url : 'albuquerquealdry.com'
    needs: build
    steps:
      - name: Clone Key Machine
        run: 
            git clone https://github.com/albuquerquealdry/key.git && cd key
      - name: Enter Directory this Connect SSH Server Dev Deploy
        run : cd key &&  ssh -i "machine.pem" ec2-user@ec2-3-16-150-13.us-east-2.compute.amazonaws.com
